name: portfolio
description: "A portfolio website designed for a flutter developer"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Thin.ttf
          weight: 100
        - asset: assets/fonts/Ubuntu/Ubuntu-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Ubuntu/Ubuntu-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Ubuntu/Ubuntu-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Ubuntu/Ubuntu-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Ubuntu/Ubuntu-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Ubuntu/Ubuntu-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Ubuntu/Ubuntu-ExtraBoldItalic.ttf
          weight: 800
          style: italic