name: portfolio
description: "A portfolio website designed for a flutter developer"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400

        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500

        - asset: assets/fonts/Ubuntu/Ubuntu-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700