name: portfolio
description: "A portfolio website designed for a flutter developer"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  responsive_framework: ^1.4.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  web: ^0.5.1
  firebase_analytics: ^11.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/icons/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400

        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500

        - asset: assets/fonts/Ubuntu/Ubuntu-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700